name: build and release

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Launch python script to make zip file for datapack and resourcepack 
          run: |
            python3 zip.py ${{ github.event.release.tag_name }} ${{ github.repository.name }}
          shell: bash
        - name: Upload datapack zip to release
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./build/${{ github.repository.name }}-${{ github.event.release.tag_name }}.zip
            asset_name: ${{ github.repository.name }}-${{ github.event.release.tag_name }}.zip
            asset_content_type: application/zip
        - name: Upload resourcepack zip to release
          uses: actions/upload-release-asset@v1
          env:
                GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./build/${{ github.repository.name }}-resourcepack-${{ github.event.release.tag_name }}.zip
            asset_name: ${{ github.repository.name }}-resourcepack-${{ github.event.release.tag_name }}.zip
            asset_content_type: application/zip

